name: Python CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install paramiko
      - name: Deploy
        run: Python deploy.py
